//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab01.Entity_Data_Modells
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class WeatherEntry
    {
        public int Id { get; set; }
        public string City { get; set; }
        public double Temperature { get; set; }
    }
}
